// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn9XszViuVP4JnzA2_Qza9AKFUz7pYm6w',
    appId: '1:117901228077:web:ebe6a8d1223b47a725e0a4',
    messagingSenderId: '117901228077',
    projectId: 'tutotial-77e5a',
    authDomain: 'tutotial-77e5a.firebaseapp.com',
    storageBucket: 'tutotial-77e5a.appspot.com',
    measurementId: 'G-MT7H34LPBJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi-uVmT5BwFKpyFXFPD1_pUP5LfFSXFes',
    appId: '1:117901228077:android:d3c58a3f153d336325e0a4',
    messagingSenderId: '117901228077',
    projectId: 'tutotial-77e5a',
    storageBucket: 'tutotial-77e5a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTGYoYoSTplQdqyfA-_0KfbzWACDJaotA',
    appId: '1:117901228077:ios:1fcf6ccf18df5d6c25e0a4',
    messagingSenderId: '117901228077',
    projectId: 'tutotial-77e5a',
    storageBucket: 'tutotial-77e5a.appspot.com',
    androidClientId: '117901228077-gba22kr154amf5eqoo7d4r03e74702vb.apps.googleusercontent.com',
    iosClientId: '117901228077-5lk7cauchgic2ea2el66vuefmjib8lm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTGYoYoSTplQdqyfA-_0KfbzWACDJaotA',
    appId: '1:117901228077:ios:1fcf6ccf18df5d6c25e0a4',
    messagingSenderId: '117901228077',
    projectId: 'tutotial-77e5a',
    storageBucket: 'tutotial-77e5a.appspot.com',
    androidClientId: '117901228077-gba22kr154amf5eqoo7d4r03e74702vb.apps.googleusercontent.com',
    iosClientId: '117901228077-5lk7cauchgic2ea2el66vuefmjib8lm7.apps.googleusercontent.com',
    iosBundleId: 'com.example.quizzer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCn9XszViuVP4JnzA2_Qza9AKFUz7pYm6w',
    appId: '1:117901228077:web:848f500b4113f49625e0a4',
    messagingSenderId: '117901228077',
    projectId: 'tutotial-77e5a',
    authDomain: 'tutotial-77e5a.firebaseapp.com',
    storageBucket: 'tutotial-77e5a.appspot.com',
    measurementId: 'G-B5F090VYRB',
  );
}
